name: common
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: gordianknot <email@example.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  colorize: ^2.0.0    #support colorizing console color

dev_dependencies:
  test: ^1.22.2
